-- ----------------------------------------------
-- DDL Statements for schemas
-- ----------------------------------------------

CREATE SCHEMA "MINIBANK";

-- ----------------------------------------------
-- DDL Statements for tables
-- ----------------------------------------------

CREATE TABLE "MINIBANK"."TRANSHISTORY" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "TRANSNAME" CHAR(8), "ACCOUNTNUMBER" CHAR(10), "TRANSAMOUNT" DOUBLE, "TRANSTIME" TIMESTAMP);

CREATE TABLE "MINIBANK"."ACCOUNT" ("ACCOUNTNUMBER" CHAR(10) NOT NULL, "CUSTOMERID" CHAR(10), "BALANCE" DOUBLE, "LASTCHANGETIME" TIMESTAMP);

CREATE TABLE "MINIBANK"."CUSTOMER" ("CUSTOMERID" CHAR(10) NOT NULL, "NAME" VARCHAR(64), "GENDER" CHAR(6), "AGE" INTEGER, "ADDRESS" VARCHAR(128));

-- ----------------------------------------------
-- DDL Statements for keys
-- ----------------------------------------------

-- PRIMARY/UNIQUE
ALTER TABLE "MINIBANK"."CUSTOMER" ADD CONSTRAINT "SQL161222154642690" PRIMARY KEY ("CUSTOMERID");

ALTER TABLE "MINIBANK"."ACCOUNT" ADD CONSTRAINT "SQL161222150859520" PRIMARY KEY ("ACCOUNTNUMBER");

ALTER TABLE "MINIBANK"."TRANSHISTORY" ADD CONSTRAINT "SQL161222172648030" PRIMARY KEY ("ID");

